#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================
ynh_print_info --message="Managing script failure..."

ynh_clean_setup () {
	ynh_clean_check_starting
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
ynh_print_info --message="Retrieving arguments from the manifest..."

domain=$YNH_APP_ARG_DOMAIN
path_url="/"

app=$YNH_APP_INSTANCE_NAME

#YOURSECRET3
focus_password=$(ynh_string_random --length=8)
#YOURSECRET1
videobridge_secret=$(ynh_string_random --length=8)
#YOURSECRET2
focus_secret=$(ynh_string_random --length=8)

focus_user="svc${app}focus"

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_print_info --message="Validating installation parameters..."

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_print_info --message="Storing installation settings..."

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=path --value=$path_url
ynh_app_setting_set --app=$app --key=focus_password --value=$focus_password
ynh_app_setting_set --app=$app --key=videobridge_secret --value=$videobridge_secret
ynh_app_setting_set --app=$app --key=focus_secret --value=$focus_secret
ynh_app_setting_set --app=$app --key=focus_user --value=$focus_user

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_print_info --message="Configuring firewall..."

# Find an available port
port=$(ynh_find_port --port=4443)
# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $port
ynh_app_setting_set --app=$app --key=port --value=$port

# Find an available port
port_videobridge=$(ynh_find_port --port=10000)
# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp UDP $port_videobridge
ynh_app_setting_set --app=$app --key=port_videobridge --value=$port_videobridge

# Find an available port
port_component=$(ynh_find_port --port=5347)
# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $port_component
ynh_app_setting_set --app=$app --key=port_component --value=$port_component

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_print_info --message="Installing dependencies..."

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# INSTALL JITSI OFFICIAL REPO
#=================================================


ynh_script_progression --message="Add Jitsi repository..."

wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
#ynh_install_extra_repo --repo="deb https://download.jitsi.org stable/" --append
touch /etc/apt/sources.list.d/jitsi.list
echo "deb https://download.jitsi.org stable/" > /etc/apt/sources.list.d/jitsi.list
apt update
ynh_app_setting_set --app=$app --key=final_path --value=$final_path

# root@scw-meet:~# /usr/bin/debconf-show jitsi-meet-prosody 
# * jicofo/jicofo-authpassword: (password omitted)
#   jitsi-videobridge/jvbsecret: (password omitted)
# * jicofo/jicofosecret: (password omitted)
#   jitsi-meet-prosody/jvb-hostname: meet.jitsi.yolops.dev
# * jicofo/jicofo-authuser: focus
#   jitsi-meet-prosody/turn-secret: QWfccoRbqHhcmu1n
# * jitsi-videobridge/jvb-hostname: meet.jitsi.yolops.dev
# root@scw-meet:~# /usr/bin/debconf-show jitsi-meet-web-config
#   jitsi-meet/cert-path-key:
#   jitsi-meet/cert-path-crt:
#   jitsi-meet/cert-choice: Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)
# * jitsi-meet/jvb-hostname: meet.jitsi.yolops.dev
# * jitsi-videobridge/jvb-hostname: meet.jitsi.yolops.dev
# root@scw-meet:~# /usr/bin/debconf-show jitsi-videobridge2
#   jitsi-videobridge/jvbsecret: (password omitted)
# * jitsi-videobridge/jvb-hostname: meet.jitsi.yolops.dev

#root@scw-meet:~# /usr/bin/debconf-show jicofo
#* jicofo/jicofo-authpassword: (password omitted)
#* jicofo/jicofosecret: (password omitted)
#* jitsi-videobridge/jvb-hostname: meet.jitsi.yolops.dev
#* jicofo/jicofo-authuser: focus
#root@scw-meet:~# /usr/bin/debconf-show jitsi-meet
#* jitsi-meet/jvb-hostname: meet.jitsi.yolops.dev
#root@scw-meet:~#

ynh_script_progression --message="debconf preset"
echo jitsi-meet jitsi-videobridge/jvb-hostname string conference.$domain | sudo debconf-set-selections

echo jicofo jicofo/jicofo-authpassword password MYSECRET | sudo debconf-set-selections
echo jicofo jicofo/jicofosecret password MYSECRET | sudo debconf-set-selections
echo jicofo jitsi-videobridge/jvb-hostname string conference.$domain | sudo debconf-set-selections
echo jicofo jicofo/jicofo-authuser string focus | sudo debconf-set-selections

echo jitsi-meet-prosody jicofo/jicofo-authpassword password MYSECRET | sudo debconf-set-selections
echo jitsi-meet-prosody jicofo/jicofosecret password MYSECRET | sudo debconf-set-selections
echo jitsi-meet-prosody jicofo/jicofo-authuser string focus | sudo debconf-set-selections
echo jitsi-meet-prosody jitsi-videobridge/jvb-hostname string conference.$domain | sudo debconf-set-selections

echo jitsi-meet-web-config jitsi-meet/jvb-hostname string conference.$domain | sudo debconf-set-selections
echo jitsi-meet-web-config jitsi-videobridge/jvb-hostname string conference.$domain | sudo debconf-set-selections

echo jitsi-videobridge2 jitsi-videobridge/jvb-hostname string conference.$domain | sudo debconf-set-selections

ynh_add_app_dependencies --package="jitsi-meet-web jitsi-meet-web-config jicofo"
ynh_add_app_dependencies --package="jitsi-videobridge2"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_print_info --message="Configuring nginx web server..."

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_print_info --message="Configuring system user..."

# Create a system user
#ynh_system_user_create --username=$app --home_dir=$final_path

#=================================================
# SPECIFIC SETUP
#=================================================
# CONFIGURE METRONOME
#=================================================
ynh_print_info --message="Configuring metronome..."

# Create additional domains
if [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
	ynh_print_info --message="Creating additional domains for package_check..."
	yunohost domain add auth.$domain
	yunohost domain add conference.$domain
	yunohost domain add jitsi-videobridge.$domain
	yunohost domain add focus.$domain
fi

# Create focus user
yunohost user create $focus_user -f $focus_user -l $focus_user -m ${focus_user}@auth.$domain -p $focus_password -q 0

# Add Metronome domain conf template
metronome_conf="/usr/share/yunohost/templates/jitsi/$domain.cfg.lua"
mkdir -p /usr/share/yunohost/templates/jitsi/
cp ../conf/metronome.cfg.lua $metronome_conf
ynh_replace_string --match_string="__DOMAIN__" --replace_string="$domain" --target_file="$metronome_conf"
ynh_replace_string --match_string="__APP__" --replace_string="$app" --target_file="$metronome_conf"
ynh_replace_string --match_string="__VIDEOBRIDGE_SECRET__" --replace_string="$videobridge_secret" --target_file="$metronome_conf"
ynh_replace_string --match_string="__FOCUS_SECRET__" --replace_string="$focus_secret" --target_file="$metronome_conf"
ynh_replace_string --match_string="__PORT_COMPONENT__" --replace_string="$port_component" --target_file="$metronome_conf"

touch "/usr/share/yunohost/templates/jitsi/auth.$domain.cfg.lua"
touch "/usr/share/yunohost/templates/jitsi/conference.$domain.cfg.lua"
touch "/usr/share/yunohost/templates/jitsi/jitsi-videobridge.$domain.cfg.lua"
touch "/usr/share/yunohost/templates/jitsi/focus.$domain.cfg.lua"

# Add Metronome hook 
cp -R ../conf/metronome_regen_conf.hook /usr/share/yunohost/hooks/conf_regen/50-metronome_$app
yunohost tools regen-conf metronome

# Add Metronome modules
cp ../conf/mod_carbons.lua /usr/lib/metronome/modules/mod_carbons.lua
cp ../conf/mod_http_altconnect.lua /usr/lib/metronome/modules/mod_http_altconnect.lua
cp ../conf/mod_smacks.lua /usr/lib/metronome/modules/mod_smacks.lua

ynh_systemd_action --service_name=metronome --action=restart

#=================================================
# BUILD JITSI-VIDEOBRIDGE
#=================================================
ynh_print_info --message="Building Jitsi-Videobridge..."

#mkdir -p "$final_path/.sip-communicator"
#cp ../conf/sip-communicator.properties "$final_path/.sip-communicator/sip-communicator.properties"
#ynh_replace_string --match_string="__PORT__" --replace_string="$port" --target_file="$final_path/.sip-communicator/sip-communicator.properties"
#chown -R $app: $final_path

#=================================================
# BUILD JITSI-JICOFO
#=================================================
ynh_print_info --message="Building Jitsi-Jicofo..."

#pushd "$final_path/jitsi-jicofo-build"
#    mvn package -DskipTests -Dassembly.skipAssembly=false
#popd
#
#unzip $final_path/jitsi-jicofo-build/target/jicofo-linux-x64-1.1-SNAPSHOT.zip -d $final_path
#
#mv $final_path/jicofo-linux-x64-1.1-SNAPSHOT/ $final_path/jitsi-jicofo/

ynh_secure_remove --file="$final_path/jitsi-jicofo-build"

#=================================================
# BUILD JITSI-MEET
#=================================================
ynh_print_info --message="Building Jitsi-Meet..."

#pushd "$final_path/jitsi-meet_temp"
#	ar x jitsi-meet-web.deb data.tar.xz
#	tar xf data.tar.xz
#popd
#
#mv "$final_path/jitsi-meet_temp/usr/share/jitsi-meet/" "$final_path/jitsi-meet/"
#ynh_secure_remove --file="$final_path/jitsi-meet_temp"
#
#/etc/jitsi/meet/meet.-config.js
config="/etc/jitsi/meet/conference.$domain.js"
cp ../conf/config.js "$config"
ynh_replace_string --match_string="__DOMAIN__" --replace_string="$domain" --target_file="$config"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_print_info --message="Configuring a systemd service..."

# Create a dedicated systemd config
#ynh_replace_string --match_string="__DOMAIN__" --replace_string="$domain" --target_file="../conf/jitsi-videobridge.service"
#ynh_replace_string --match_string="__VIDEOBRIDGE_SECRET__" --replace_string="$videobridge_secret" --target_file="../conf/jitsi-videobridge.service"
#ynh_replace_string --match_string="__PORT_COMPONENT__" --replace_string="$port_component" --target_file="../conf/jitsi-videobridge.service"
#ynh_add_systemd_config --service=$app-videobridge --template="jitsi-videobridge.service"
#
#ynh_replace_string --match_string="__DOMAIN__" --replace_string="$domain" --target_file="../conf/jitsi-jicofo.service"
#ynh_replace_string --match_string="__FOCUS_SECRET__" --replace_string="$focus_secret" --target_file="../conf/jitsi-jicofo.service"
#ynh_replace_string --match_string="__FOCUS_USER__" --replace_string="$focus_user" --target_file="../conf/jitsi-jicofo.service"
#ynh_replace_string --match_string="__FOCUS_PASSWORD__" --replace_string="$focus_password" --target_file="../conf/jitsi-jicofo.service"
#ynh_add_systemd_config --service=$app-jicofo --template="jitsi-jicofo.service"

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================
ynh_print_info --message="Storing the config file checksum..."

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum --file="$config"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_print_info --message="Securing files and directories..."

# Set permissions to app files
chown -R $app: $final_path

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_print_info --message="Configuring log rotation..."

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_print_info --message="Integrating service in YunoHost..."

yunohost service add $app-videobridge --description "$app jitsi-videobridge for jitsi" --log "/var/log/$app/$app-videobridge.log"
yunohost service add $app-jicofo --description "$app jitsi-jicofo for jitsi" --log "/var/log/$app/$app-jicofo.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_print_info --message="Starting a systemd service..."

# Start a systemd service
ynh_systemd_action --service_name=$app-videobridge --action="start" --log_path="/var/log/$app/$app-videobridge.log"
ynh_systemd_action --service_name=$app-jicofo --action="start" --log_path="/var/log/$app/$app-jicofo.log"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_print_info --message="Configuring SSOwat..."

# Make app public
ynh_app_setting_set --app=$app --key=unprotected_uris --value="/"

#=================================================
# RELOAD NGINX
#=================================================
ynh_print_info --message="Reloading nginx web server..."

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Installation of $app completed"
